name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/mydatabase

  merge-check:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/mydatabase
